<!--Body content-->
<div class="row-fluid">

	<!-- Modal Account Add -->
	<div id="addGoalCashData" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addGoalCashDataAddLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="addGoalCashDataAddLabel">Add cash to Goal</h3>
		</div>
		<form id="<?=$this->addGoalCashForm->getId()?>" class="<?=$this->addGoalCashForm->getAttrib('class')?>" name="<?=$this->addGoalCashForm->getName()?>" enctype="<?=$this->addGoalCashForm->getEnctype()?>" method="<?=$this->addGoalCashForm->getMethod()?>" action="<?=$this->addGoalCashForm->getAction()?>">
			<div class="modal-body">
				<ul class='unstyled'>
					<li>
						<?=$this->addGoalCashForm->goal_id?>
					</li>
					<li>
						<?=$this->addGoalCashForm->amount?>
					</li>
				</ul>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				<?=$this->addGoalCashForm->Add?>
			</div>
		</form>
	</div>
	<!-- Modal Account Add End-->

	<div class="row-fluid">
		<div class="offset5"><h4>Goal Details: <?=$this->escape($this->goalData->name)?></h4></div>
	</div>
	<div class="row-fluid">
		<div class="span6"><b>Goal amount: </b><?=$this->escape($this->goalData->amount)?> <?=$this->escape($this->goalData->getBankAccountsCurrency())?></div>
		<div class="span6"><b>Description: </b><?=$this->escape($this->goalData->description)?></div>
	</div>
	<div class="row-fluid">
		<div class="span6"><b>Exp Date: </b><?=$this->escape($this->goalData->getGoalDate())?></div>
		<div class="span6"><b>Bank account: </b><?=$this->escape($this->goalData->getBankAccountsNames())?></div>
	</div>
	<div class="row-fluid">
		<div class="span4" style="text-align:left">0 <?=$this->escape($this->goalData->getBankAccountsCurrency())?></div>
		<div class="span4" style="text-align:center"><?=$this->escape($this->goalData->getGoalCurrentAmount())?> <?=$this->escape($this->goalData->getBankAccountsCurrency())?></div>
		<div class="span4" style="text-align:right"><?=$this->escape($this->goalData->amount)?> <?=$this->escape($this->goalData->getBankAccountsCurrency())?></div>
	</div>
	<div class="row-fluid">
		<div class="progress progress-info progress-striped active">
			<div class="bar" style="width: <?=($this->escape($this->goalData->getGoalCurrentAmount())/$this->escape($this->goalData->amount))*100?>%"></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
<?php if ($this->escape($this->goalData->getBankAccountsNames()) == 'Cash') {?>
					<a class="span12 btn btn-large btn btn-success" onclick="document.getElementById('goal_id').value=<?=$this->goalData->id?>" href="#addGoalCashData" data-toggle="modal">Add Cash</a>
<?php } else { ?>
					<a class="span12 btn btn-large btn btn-success" href="/bank/addPayments?id=<?=$this->escape($this->goalData->getBankAccountsIds())?>" data-toggle="modal">Add Cash</a>
<?php } ?>
		</div>
		<div class="span6">
			<a class="span12 btn btn-large btn btn-danger" href="/goal/deleteGoal?id=<?=$this->goalData->id?>" data-toggle="modal">Finish Goal</a>
		</div>
	</div>
</div>
