<ul id="bankMenu" class="nav nav-tabs">
	<li class="<?=$this->action == 'viewPayments' ? 'active' : ''?>">
		<a href="/bank/viewPayments">View Payments</a>
	</li>
	<li class="<?=$this->action == 'addPayments' ? 'active' : ''?>">
		<a href="/bank/addPayments">Add Payments</a>
	</li>
	<li class="<?=$this->action == 'configure' ? 'active' : ''?>">
		<a href="/bank/configure">Configure</a>
	</li>
</ul>

