<div class="row-fluid">
	<ul class="pager">
		<div class="span4">
<? if ($this->form->offset->getValue() != 0) { ?>
		<li class="previous"><a id="paginator_left" href="#">&larr; Newer</a></li>
<? } ?>
		</div>
		<div class="span4" style="text-align:center">
			<li>
				<a>Showing <?=$this->form->offset->getValue()?> - <?=$this->form->offset->getValue() + $this->form->limit->getValue()?> of <?=$this->totalCount?></a>
			</li>
		</div>
		<div class="span4">
<? if ($this->totalCount > $this->form->offset->getValue() + $this->form->limit->getValue()) { ?>
		<li class="next"><a id="paginator_right" href="#">Older &rarr;</a></li>
<? } ?>
		</div>
	</ul>
</div>
