<form id="<?=$this->form->getId()?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" action="<?=$this->form->getAction()?>" method="<?=$this->form->getMethod()?>">
	<legend>Register for an account</legend>
	<table>
<?if ($this->__isset('error') && count($this->error)) {
if (in_array('dataInvalid', $this->error)) $error_message = 'Credentials You used is not valid.';
if (in_array('passwordsNotMatch', $this->error)) $error_message = 'Passwords didn\'t match	.';
?>
		<tr>
			<td><p class="alert alert-error form-alert"><?=$error_message?></p></td>
		</tr>
<? } ?>
		<tr>
			<td><?=$this->form->nickname?></td>
		</tr>
		<tr>
			<td><?=$this->form->email?></td>
		</tr>
		<tr>
			<td><?=$this->form->password?></td>
		</tr>
		<tr>
			<td><?=$this->form->password_confirm?></td>
		</tr>
<?if ($this->form->ReCaptcha) {?>
		<tr>
			<td><?=$this->form->ReCaptcha?></td>
		</tr>
<? } ?>
		<tr>
			<td><?=$this->form->Register?></td>
		</tr>
	</table>
</form>

