<form id="<?=$this->form->getId()?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" method="<?=$this->form->getMethod()?>" action="<?=$this->form->getAction()?>">
	<legend>Reset password</legend>
	<table>
		<tr>
			<td><?=$this->form->email?></td>
		</tr>
<?if ($this->form->ReCaptcha) {?>
		<tr>
			<td><?=$this->form->ReCaptcha?></td>
		</tr>
<? } ?>
		<tr>
			<td><?=$this->form->Reset?></td>
		</tr>
	</table>
</form>

