<?=$this->render('partials/bankMenu.phtml')?>
<div class="row-fluid">
	<div class="span4" id="addPayment">
		<h4 class="offset2">Add Bank Payment</h4>
		<form id="<?=$this->addPaymentForm->getId()?>" class="<?=$this->addPaymentForm->getAttrib('class')?>" name="<?=$this->addPaymentForm->getName()?>" enctype="<?=$this->addPaymentForm->getEnctype()?>" method="<?=$this->addPaymentForm->getMethod()?>" action="<?=$this->addPaymentForm->getAction()?>">
			<ul class='unstyled'>
				<li>
<?=$this->addPaymentForm->bank_account_id?>
				</li>
				<li>
<?=$this->addPaymentForm->action?>
				</li>
				<li>
<?=$this->addPaymentForm->amount?>
				</li>
				<li>
<?=$this->addPaymentForm->description?>
				</li>
				<li>
<?=$this->addPaymentForm->Add?>
				</li>
			</ul>
		</form>
	</div>
</div>

