<?=$this->render('partials/bankMenu.phtml')?>
<div class="row-fluid">
	<h4 class="offset5">Bank Payments</h4>
<?if ($this->paymentHistory->count()) {?>
	<div class="navbar">
		<div class="navbar-inner">
			<form id="<?=$this->form->getId()?>" class="<?=$this->form->getAttrib('class')?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" method="<?=$this->form->getMethod()?>" action="<?=$this->form->getAction()?>">
	<?=$this->form->limit?>
	<?=$this->form->offset?>
					<ul class="nav">
						<li><a href='#' id='limit_10' style="padding-right:5px;padding-left:5px">10</a></li>
						<li><a href='#' id='limit_25' style="padding-right:5px;padding-left:5px">25</a></li>
						<li><a href='#' id='limit_50' style="padding-right:5px;padding-left:5px">50</a></li>
					</ul>
					<div class="nav">
<?=$this->form->account_name?>
<?=$this->form->bank_action?>
<?=$this->form->dateFrom?>
<?=$this->form->dateTo?>
<?=$this->form->searchString?>
<?=$this->form->Search?>
					</div>
			</form>
		</div>
	</div>

<?=$this->render('partials/paginator.phtml')?>
	<table class="table">
		<tr>
				<td><b>Name</b></td>
				<td><b>Action</b></td>
				<td><b>Amount</b></td>
				<td><b>Currency</b></td>
				<td><b>Date</b></td>
				<td><b>Description</b></td>
		</tr>
<?foreach ($this->paymentHistory as $row) {?>
				<td><?=$this->escape($row->getBankAccountName())?></td>
				<td><?=$this->escape($row->getBankAccountActivityAction())?></td>
				<td><?=$this->escape($row->getBankAccountActivityAmount())?></td>
				<td><?=$this->escape($row->getBankAccountActivityCurrency())?></td>
				<td><?=$row->getFormattedDate()?></td>
				<td><?=$this->escape($row->description)?></td>
		</tr>
<? } ?>
	</table>
<? } else { ?>
	<p>No records found.</p>
<? } ?>
</div>
