<?=$this->render('partials/utilitiesMenu.phtml')?>
<div class="tab-content">
	<div class="tab-pane active in" id="viewPayment">
		<h4 class="offset4">History of Utility Payments</h4>
		<!-- navbar start -->
		<div class="navbar">
			<div class="navbar-inner">
				<form id="<?=$this->form->getId()?>" class="<?=$this->form->getAttrib('class')?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" method="<?=$this->form->getMethod()?>" action="<?=$this->form->getAction()?>">
		<?=$this->form->limit?>
		<?=$this->form->offset?>
						<ul class="nav">
							<li><a href='#' id='limit_10' style="padding-right:5px;padding-left:5px">10</a></li>
							<li><a href='#' id='limit_25' style="padding-right:5px;padding-left:5px">25</a></li>
							<li><a href='#' id='limit_50' style="padding-right:5px;padding-left:5px">50</a></li>
						</ul>
						<div class="nav">
	<?=$this->form->utility_name?>
	<?=$this->form->provider_name?>
	<?=$this->form->dateFrom?><?=$this->form->dateTo?>
	<?=$this->form->searchString?>
	<?=$this->form->Search?>
						</div>
				</form>
			</div>
		</div>
		<!-- navbar end -->
<?if ($this->utilityPaymentsHistory->count()) {?>
<?=$this->render('partials/paginator.phtml')?>
		<table class="table">
			<tr>
					<td><b>Utility</b></td>
					<td><b>Provider</b></td>
					<td><b>Amount</b></td>
					<td><b>Currency</b></td>
					<td><b>Period (From)</b></td>
					<td><b>Period (To)</b></td>
					<td><b>Description</b></td>
			</tr>
<?foreach ($this->utilityPaymentsHistory as $utilityPayment) {?>
			<tr>
					<td><?=$this->escape($utilityPayment->getPaymentUtilityName())?></td>
					<td><?=$this->escape($utilityPayment->getPaymentProviderName())?></td>
					<td><?=$this->escape($utilityPayment->getPaymentAmount())?></td>
					<td><?=$this->escape($utilityPayment->getPaymentCurrency())?></td>
					<td><?=$this->escape($utilityPayment->getPaymentFromDate())?></td>
					<td><?=$this->escape($utilityPayment->getPaymentToDate())?></td>
					<td><?=$this->escape($utilityPayment->description)?></td>
			</tr>
<? } ?>
		</table>
<? } else { ?>
		<p>No records found.</p>
<? } ?>
	</div>
</div>
